// ============================================================================
// QUANTUM SETUP HTML - Setup Dialog Generator
// ============================================================================
// Generates the HTML for the quantum setup/configuration dialog.
// ============================================================================

/**
 * Returns the full HTML string for the quantum setup dialog.
 * Features a dark gradient background, glassmorphism container,
 * pulsing quantum logo, feature grid, configuration form,
 * and deployment controls.
 *
 * @return {string} Complete HTML string for the setup dialog.
 */
function getQuantumSetupHTML() {
  var html = '<!DOCTYPE html>'
    + '<html>'
    + '<head>'
    + '<style>'
    + '* { margin: 0; padding: 0; box-sizing: border-box; }'
    + 'body {'
    + '  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;'
    + '  background: linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%);'
    + '  min-height: 100vh;'
    + '  display: flex;'
    + '  justify-content: center;'
    + '  align-items: center;'
    + '  padding: 20px;'
    + '  color: #fff;'
    + '}'
    + '.container {'
    + '  background: rgba(255, 255, 255, 0.08);'
    + '  backdrop-filter: blur(20px);'
    + '  -webkit-backdrop-filter: blur(20px);'
    + '  border: 1px solid rgba(255, 255, 255, 0.15);'
    + '  border-radius: 20px;'
    + '  padding: 40px;'
    + '  max-width: 700px;'
    + '  width: 100%;'
    + '  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);'
    + '}'
    + '.quantum-logo {'
    + '  text-align: center;'
    + '  font-size: 48px;'
    + '  margin-bottom: 10px;'
    + '  animation: pulse 2s ease-in-out infinite;'
    + '}'
    + '@keyframes pulse {'
    + '  0%, 100% { transform: scale(1); opacity: 1; }'
    + '  50% { transform: scale(1.1); opacity: 0.8; }'
    + '}'
    + '.title {'
    + '  text-align: center;'
    + '  font-size: 28px;'
    + '  font-weight: bold;'
    + '  background: linear-gradient(90deg, #667eea, #764ba2, #f093fb);'
    + '  -webkit-background-clip: text;'
    + '  -webkit-text-fill-color: transparent;'
    + '  background-clip: text;'
    + '  margin-bottom: 30px;'
    + '}'
    + '.feature-grid {'
    + '  display: grid;'
    + '  grid-template-columns: repeat(4, 1fr);'
    + '  gap: 12px;'
    + '  margin-bottom: 30px;'
    + '}'
    + '.feature-item {'
    + '  background: rgba(255, 255, 255, 0.06);'
    + '  border: 1px solid rgba(255, 255, 255, 0.1);'
    + '  border-radius: 12px;'
    + '  padding: 12px 8px;'
    + '  text-align: center;'
    + '  font-size: 12px;'
    + '  transition: transform 0.2s;'
    + '}'
    + '.feature-item:hover { transform: translateY(-2px); }'
    + '.feature-icon { font-size: 24px; margin-bottom: 6px; }'
    + '.form-group {'
    + '  margin-bottom: 16px;'
    + '}'
    + '.form-group label {'
    + '  display: block;'
    + '  font-size: 13px;'
    + '  color: rgba(255, 255, 255, 0.7);'
    + '  margin-bottom: 6px;'
    + '}'
    + '.form-group input, .form-group select {'
    + '  width: 100%;'
    + '  padding: 10px 14px;'
    + '  background: rgba(255, 255, 255, 0.08);'
    + '  border: 1px solid rgba(255, 255, 255, 0.2);'
    + '  border-radius: 10px;'
    + '  color: #fff;'
    + '  font-size: 14px;'
    + '  outline: none;'
    + '  transition: border-color 0.3s;'
    + '}'
    + '.form-group input:focus, .form-group select:focus {'
    + '  border-color: #667eea;'
    + '}'
    + '.form-group input::placeholder { color: rgba(255, 255, 255, 0.35); }'
    + '.form-group select option { background: #302b63; color: #fff; }'
    + '.form-row { display: flex; gap: 16px; }'
    + '.form-row .form-group { flex: 1; }'
    + '.deploy-btn {'
    + '  width: 100%;'
    + '  padding: 14px;'
    + '  background: linear-gradient(135deg, #667eea, #764ba2);'
    + '  border: none;'
    + '  border-radius: 12px;'
    + '  color: #fff;'
    + '  font-size: 16px;'
    + '  font-weight: bold;'
    + '  cursor: pointer;'
    + '  margin-top: 10px;'
    + '  transition: transform 0.2s, box-shadow 0.2s;'
    + '}'
    + '.deploy-btn:hover {'
    + '  transform: translateY(-2px);'
    + '  box-shadow: 0 6px 20px rgba(102, 126, 234, 0.4);'
    + '}'
    + '.loading-overlay {'
    + '  display: none;'
    + '  position: fixed;'
    + '  top: 0; left: 0; right: 0; bottom: 0;'
    + '  background: rgba(15, 12, 41, 0.95);'
    + '  justify-content: center;'
    + '  align-items: center;'
    + '  flex-direction: column;'
    + '  z-index: 1000;'
    + '}'
    + '.loading-overlay.active { display: flex; }'
    + '.spinner {'
    + '  width: 60px;'
    + '  height: 60px;'
    + '  border: 4px solid rgba(255, 255, 255, 0.1);'
    + '  border-top-color: #667eea;'
    + '  border-radius: 50%;'
    + '  animation: spin 1s linear infinite;'
    + '  margin-bottom: 20px;'
    + '}'
    + '@keyframes spin { to { transform: rotate(360deg); } }'
    + '.loading-status {'
    + '  font-size: 16px;'
    + '  color: rgba(255, 255, 255, 0.8);'
    + '  text-align: center;'
    + '}'
    + '.message {'
    + '  display: none;'
    + '  padding: 14px;'
    + '  border-radius: 10px;'
    + '  margin-top: 16px;'
    + '  text-align: center;'
    + '  font-size: 14px;'
    + '}'
    + '.message.success {'
    + '  display: block;'
    + '  background: rgba(72, 187, 120, 0.2);'
    + '  border: 1px solid rgba(72, 187, 120, 0.4);'
    + '  color: #68d391;'
    + '}'
    + '.message.error {'
    + '  display: block;'
    + '  background: rgba(245, 101, 101, 0.2);'
    + '  border: 1px solid rgba(245, 101, 101, 0.4);'
    + '  color: #fc8181;'
    + '}'
    + '</style>'
    + '</head>'
    + '<body>'
    + '<div class="container">'
    + '  <div class="quantum-logo">&#9883;</div>'
    + '  <div class="title">CarHawk Quantum Setup</div>'
    + ''
    + '  <div class="feature-grid">'
    + '    <div class="feature-item"><div class="feature-icon">&#129302;</div>AI Analysis</div>'
    + '    <div class="feature-item"><div class="feature-icon">&#128200;</div>Market Data</div>'
    + '    <div class="feature-item"><div class="feature-icon">&#127919;</div>Scoring</div>'
    + '    <div class="feature-item"><div class="feature-icon">&#9881;</div>Workflows</div>'
    + '    <div class="feature-item"><div class="feature-icon">&#128202;</div>Analytics</div>'
    + '    <div class="feature-item"><div class="feature-icon">&#128276;</div>Alerts</div>'
    + '    <div class="feature-item"><div class="feature-icon">&#128172;</div>SMS-iT</div>'
    + '    <div class="feature-item"><div class="feature-icon">&#128161;</div>Ohmylead</div>'
    + '  </div>'
    + ''
    + '  <form id="setupForm">'
    + '    <div class="form-row">'
    + '      <div class="form-group">'
    + '        <label>Business Name</label>'
    + '        <input type="text" id="businessName" placeholder="Your Business Name" required />'
    + '      </div>'
    + '      <div class="form-group">'
    + '        <label>Home ZIP Code</label>'
    + '        <input type="text" id="homeZip" value="63101" required />'
    + '      </div>'
    + '    </div>'
    + ''
    + '    <div class="form-group">'
    + '      <label>OpenAI API Key</label>'
    + '      <input type="password" id="openaiKey" placeholder="sk-..." required />'
    + '    </div>'
    + ''
    + '    <div class="form-row">'
    + '      <div class="form-group">'
    + '        <label>SMS-iT API Key (Optional)</label>'
    + '        <input type="text" id="smsitKey" placeholder="SMS-iT API Key" />'
    + '      </div>'
    + '      <div class="form-group">'
    + '        <label>Ohmylead Webhook (Optional)</label>'
    + '        <input type="text" id="ohmyleadWebhook" placeholder="https://..." />'
    + '      </div>'
    + '    </div>'
    + ''
    + '    <div class="form-row">'
    + '      <div class="form-group">'
    + '        <label>Profit Target ($)</label>'
    + '        <input type="number" id="profitTarget" value="2000" required />'
    + '      </div>'
    + '      <div class="form-group">'
    + '        <label>Analysis Depth</label>'
    + '        <select id="analysisDepth">'
    + '          <option value="Quantum">Quantum</option>'
    + '          <option value="Advanced">Advanced</option>'
    + '          <option value="Basic">Basic</option>'
    + '        </select>'
    + '      </div>'
    + '    </div>'
    + ''
    + '    <div class="form-group">'
    + '      <label>Alert Email</label>'
    + '      <input type="email" id="alertEmail" placeholder="alerts@yourbusiness.com" required />'
    + '    </div>'
    + ''
    + '    <button type="button" class="deploy-btn" onclick="deploySystem()">Deploy Quantum Architecture</button>'
    + '    <div id="successMsg" class="message"></div>'
    + '    <div id="errorMsg" class="message"></div>'
    + '  </form>'
    + '</div>'
    + ''
    + '<div id="loadingOverlay" class="loading-overlay">'
    + '  <div class="spinner"></div>'
    + '  <div id="loadingStatus" class="loading-status">Initializing Quantum Architecture...</div>'
    + '</div>'
    + ''
    + '<script>'
    + 'function deploySystem() {'
    + '  var config = {'
    + '    businessName: document.getElementById("businessName").value,'
    + '    homeZip: document.getElementById("homeZip").value,'
    + '    openaiKey: document.getElementById("openaiKey").value,'
    + '    smsitKey: document.getElementById("smsitKey").value,'
    + '    ohmyleadWebhook: document.getElementById("ohmyleadWebhook").value,'
    + '    profitTarget: document.getElementById("profitTarget").value,'
    + '    analysisDepth: document.getElementById("analysisDepth").value,'
    + '    alertEmail: document.getElementById("alertEmail").value'
    + '  };'
    + ''
    + '  if (!config.businessName || !config.openaiKey || !config.alertEmail) {'
    + '    showError("Please fill in all required fields.");'
    + '    return;'
    + '  }'
    + ''
    + '  showLoading();'
    + '  updateStatus("Deploying quantum architecture...");'
    + ''
    + '  google.script.run'
    + '    .withSuccessHandler(function(result) {'
    + '      hideLoading();'
    + '      showSuccess("Quantum architecture deployed successfully! System is now active.");'
    + '    })'
    + '    .withFailureHandler(function(error) {'
    + '      hideLoading();'
    + '      showError("Deployment failed: " + error.message);'
    + '    })'
    + '    .deployQuantumArchitecture(config);'
    + '}'
    + ''
    + 'function showLoading() {'
    + '  document.getElementById("loadingOverlay").classList.add("active");'
    + '}'
    + ''
    + 'function hideLoading() {'
    + '  document.getElementById("loadingOverlay").classList.remove("active");'
    + '}'
    + ''
    + 'function updateStatus(msg) {'
    + '  document.getElementById("loadingStatus").textContent = msg;'
    + '}'
    + ''
    + 'function showSuccess(msg) {'
    + '  var el = document.getElementById("successMsg");'
    + '  el.textContent = msg;'
    + '  el.className = "message success";'
    + '  document.getElementById("errorMsg").className = "message";'
    + '}'
    + ''
    + 'function showError(msg) {'
    + '  var el = document.getElementById("errorMsg");'
    + '  el.textContent = msg;'
    + '  el.className = "message error";'
    + '  document.getElementById("successMsg").className = "message";'
    + '}'
    + '</script>'
    + '</body>'
    + '</html>';

  return html;
}
